"""Seeded microcontroller controller catalog."""

from __future__ import annotations

from .models import ControllerSpec

SEED_CONTROLLERS: list[ControllerSpec] = [
    ControllerSpec(
        controller_id="arduino-uno",
        name="Arduino Uno",
        family="AVR",
        description="Classic ATmega328P board for learning and prototyping.",
        voltage_v=5.0,
        clock_mhz=16.0,
        flash_kb=32,
        ram_kb=2,
        digital_pins=14,
        analog_pins=6,
        pwm_pins=6,
        supports_onewire=True,
        tags=["beginner", "5v", "avr"],
    ),
    ControllerSpec(
        controller_id="arduino-mega",
        name="Arduino Mega 2560",
        family="AVR",
        description="Large AVR board with extended GPIO for complex projects.",
        voltage_v=5.0,
        clock_mhz=16.0,
        flash_kb=256,
        ram_kb=8,
        digital_pins=54,
        analog_pins=16,
        pwm_pins=15,
        supports_onewire=True,
        tags=["5v", "avr", "many-pins"],
    ),
    ControllerSpec(
        controller_id="esp32",
        name="ESP32",
        family="Espressif",
        description="Dual-core Wi-Fi + Bluetooth SoC with rich peripherals.",
        voltage_v=3.3,
        clock_mhz=240.0,
        flash_kb=4096,
        ram_kb=520,
        digital_pins=34,
        analog_pins=18,
        pwm_pins=16,
        supports_onewire=True,
        supports_wifi=True,
        supports_bluetooth=True,
        tags=["wifi", "ble", "iot"],
    ),
    ControllerSpec(
        controller_id="esp8266",
        name="ESP8266",
        family="Espressif",
        description="Low-cost Wi-Fi microcontroller for IoT nodes.",
        voltage_v=3.3,
        clock_mhz=80.0,
        flash_kb=4096,
        ram_kb=80,
        digital_pins=11,
        analog_pins=1,
        pwm_pins=4,
        supports_wifi=True,
        tags=["wifi", "iot", "low-cost"],
    ),
    ControllerSpec(
        controller_id="raspberry-pi-pico",
        name="Raspberry Pi Pico",
        family="RP2040",
        description="Dual-core RP2040 board with flexible PIO and low power.",
        voltage_v=3.3,
        clock_mhz=133.0,
        flash_kb=2048,
        ram_kb=264,
        digital_pins=26,
        analog_pins=3,
        pwm_pins=16,
        tags=["rp2040", "pio", "micropython"],
    ),
    ControllerSpec(
        controller_id="stm32",
        name="STM32 (Blue Pill)",
        family="STM32",
        description="ARM Cortex-M3 development board for industrial applications.",
        voltage_v=3.3,
        clock_mhz=72.0,
        flash_kb=64,
        ram_kb=20,
        digital_pins=37,
        analog_pins=10,
        pwm_pins=12,
        supports_spi=True,
        tags=["arm", "industrial", "cortex-m3"],
    ),
]
