"""Seeded hardware component catalog."""

from __future__ import annotations

from .models import ComponentSpec, PinRequirement

SEED_COMPONENTS: list[ComponentSpec] = [
    ComponentSpec(
        component_id="dht11",
        name="DHT11",
        category="sensor",
        description="Basic digital temperature and humidity sensor (±2°C, 20-80% RH).",
        interfaces=["digital"],
        voltage_v=3.3,
        current_ma=2.5,
        pins=PinRequirement(count=1, interfaces=["digital"], notes="Single data pin + VCC/GND"),
        libraries=["DHT sensor library"],
        tags=["temperature", "humidity", "environment"],
    ),
    ComponentSpec(
        component_id="dht22",
        name="DHT22",
        category="sensor",
        description="High-precision digital temperature and humidity sensor (±0.5°C).",
        interfaces=["digital"],
        voltage_v=3.3,
        current_ma=1.5,
        pins=PinRequirement(count=1, interfaces=["digital"]),
        libraries=["DHT sensor library"],
        tags=["temperature", "humidity", "environment", "precision"],
    ),
    ComponentSpec(
        component_id="hc-sr04",
        name="HC-SR04",
        category="sensor",
        description="Ultrasonic distance sensor, 2 cm to 400 cm range.",
        interfaces=["digital"],
        voltage_v=5.0,
        current_ma=15.0,
        pins=PinRequirement(count=2, interfaces=["digital"], notes="TRIG + ECHO"),
        libraries=["NewPing"],
        tags=["distance", "ultrasonic", "proximity"],
    ),
    ComponentSpec(
        component_id="pir",
        name="PIR Motion Sensor",
        category="sensor",
        description="Passive infrared motion detector for occupancy sensing.",
        interfaces=["digital"],
        voltage_v=5.0,
        current_ma=50.0,
        pins=PinRequirement(count=1, interfaces=["digital"]),
        tags=["motion", "security", "occupancy"],
    ),
    ComponentSpec(
        component_id="mq2",
        name="MQ-2 Gas Sensor",
        category="sensor",
        description="Combustible gas and smoke sensor (LPG, propane, methane, smoke).",
        interfaces=["analog", "digital"],
        voltage_v=5.0,
        current_ma=150.0,
        pins=PinRequirement(count=2, interfaces=["analog", "digital"]),
        tags=["gas", "smoke", "safety"],
    ),
    ComponentSpec(
        component_id="soil-moisture",
        name="Soil Moisture Sensor",
        category="sensor",
        description="Capacitive or resistive soil moisture probe for irrigation systems.",
        interfaces=["analog"],
        voltage_v=3.3,
        current_ma=5.0,
        pins=PinRequirement(count=1, interfaces=["analog"]),
        tags=["agriculture", "irrigation", "moisture"],
    ),
    ComponentSpec(
        component_id="led",
        name="LED",
        category="actuator",
        description="Standard indicator light-emitting diode.",
        interfaces=["digital", "pwm"],
        voltage_v=3.3,
        current_ma=20.0,
        pins=PinRequirement(count=1, interfaces=["digital", "pwm"]),
        tags=["indicator", "light"],
    ),
    ComponentSpec(
        component_id="relay",
        name="Relay Module",
        category="actuator",
        description="Single-channel relay module for switching high-voltage loads.",
        interfaces=["digital"],
        voltage_v=5.0,
        current_ma=70.0,
        pins=PinRequirement(count=1, interfaces=["digital"]),
        tags=["switch", "actuator", "power"],
    ),
    ComponentSpec(
        component_id="servo",
        name="Servo Motor",
        category="actuator",
        description="Standard hobby servo motor (SG90 class), 0-180° positional control.",
        interfaces=["pwm"],
        voltage_v=5.0,
        current_ma=500.0,
        pins=PinRequirement(count=1, interfaces=["pwm"]),
        libraries=["Servo"],
        tags=["motor", "position", "robotics"],
    ),
    ComponentSpec(
        component_id="lcd",
        name="LCD 16x2",
        category="display",
        description="16×2 character LCD with HD44780 controller (I2C backpack supported).",
        interfaces=["i2c", "digital"],
        voltage_v=5.0,
        current_ma=80.0,
        pins=PinRequirement(count=2, interfaces=["i2c"], notes="I2C backpack: SDA/SCL"),
        libraries=["LiquidCrystal I2C"],
        tags=["display", "text", "ui"],
    ),
]
