"""Generate data/components/*.json catalog entries."""
from __future__ import annotations

import json
from pathlib import Path


def pin(name: str, typ: str, **kw):
    return {"name": name, "type": typ, **kw}


def comp(
    cid,
    name,
    category,
    manufacturer,
    interfaces,
    voltage,
    pins,
    keywords,
    aliases=None,
    controllers=None,
    simulation=None,
    description="",
):
    vmin, vmax = voltage if isinstance(voltage, tuple) else (voltage, voltage)
    return {
        "id": cid,
        "name": name,
        "category": category,
        "manufacturer": manufacturer,
        "description": description or name,
        "interfaces": interfaces,
        "voltage": {"min": vmin, "max": vmax},
        "pins": pins,
        "keywords": keywords,
        "aliases": aliases or [],
        "compatible_controllers": controllers
        or ["esp32", "arduino-uno", "stm32", "raspberry-pi-pico"],
        "simulation": simulation or {"supported": True, "model": cid.replace("-", "_")},
    }


def main() -> None:
    root = Path(__file__).resolve().parents[1] / "data" / "components"
    root.mkdir(parents=True, exist_ok=True)
    items = []

    items += [
        comp(
            "arduino-uno",
            "Arduino Uno",
            "mcu",
            "Arduino",
            ["GPIO", "PWM", "UART", "I2C", "SPI", "ADC"],
            (5, 5),
            [
                pin("D13", "GPIO"),
                pin("D2", "GPIO"),
                pin("A0", "ADC"),
                pin("5V", "POWER"),
                pin("GND", "GROUND"),
                pin("SDA", "I2C"),
                pin("SCL", "I2C"),
            ],
            ["arduino", "uno", "mcu", "microcontroller"],
            ["uno", "arduino uno"],
            ["arduino-uno"],
        ),
        comp(
            "arduino-mega",
            "Arduino Mega",
            "mcu",
            "Arduino",
            ["GPIO", "PWM", "UART", "I2C", "SPI", "ADC"],
            (5, 5),
            [pin("D13", "GPIO"), pin("A0", "ADC"), pin("5V", "POWER"), pin("GND", "GROUND")],
            ["arduino", "mega", "mcu"],
            ["mega"],
            ["arduino-uno", "arduino-mega"],
        ),
        comp(
            "esp32",
            "ESP32 DevKit",
            "mcu",
            "Espressif",
            ["GPIO", "PWM", "UART", "I2C", "SPI", "ADC", "WiFi", "Bluetooth"],
            (3.3, 3.3),
            [
                pin("D2", "GPIO"),
                pin("D4", "GPIO"),
                pin("D21", "I2C"),
                pin("D22", "I2C"),
                pin("3V3", "POWER"),
                pin("GND", "GROUND"),
                pin("TX", "UART"),
                pin("RX", "UART"),
                pin("MOSI", "SPI"),
                pin("MISO", "SPI"),
                pin("SCK", "SPI"),
            ],
            ["esp", "esp32", "wifi", "bluetooth", "mcu"],
            ["esp 32"],
            ["esp32"],
        ),
        comp(
            "esp8266",
            "ESP8266 NodeMCU",
            "mcu",
            "Espressif",
            ["GPIO", "PWM", "UART", "I2C", "SPI", "ADC", "WiFi"],
            (3.3, 3.3),
            [pin("D1", "GPIO"), pin("D2", "GPIO"), pin("3V3", "POWER"), pin("GND", "GROUND")],
            ["esp", "esp8266", "wifi", "mcu"],
            ["nodemcu"],
            ["esp8266", "esp32"],
        ),
        comp(
            "stm32",
            "STM32 Blue Pill",
            "mcu",
            "STMicroelectronics",
            ["GPIO", "PWM", "UART", "I2C", "SPI", "ADC"],
            (3.3, 3.3),
            [
                pin("PA0", "GPIO"),
                pin("PB6", "I2C"),
                pin("PB7", "I2C"),
                pin("3V3", "POWER"),
                pin("GND", "GROUND"),
            ],
            ["stm32", "blue pill", "mcu"],
            ["bluepill", "blue pill"],
            ["stm32"],
        ),
        comp(
            "raspberry-pi-pico",
            "Raspberry Pi Pico",
            "mcu",
            "Raspberry Pi",
            ["GPIO", "PWM", "UART", "I2C", "SPI", "ADC"],
            (3.3, 3.3),
            [
                pin("GP0", "GPIO"),
                pin("GP4", "I2C"),
                pin("GP5", "I2C"),
                pin("3V3", "POWER"),
                pin("GND", "GROUND"),
            ],
            ["pico", "raspberry", "rp2040", "mcu"],
            ["pico"],
            ["raspberry-pi-pico"],
        ),
        comp(
            "raspberry-pi-4",
            "Raspberry Pi 4",
            "mcu",
            "Raspberry Pi",
            ["GPIO", "PWM", "UART", "I2C", "SPI", "WiFi", "Bluetooth"],
            (3.3, 5),
            [
                pin("GPIO2", "I2C"),
                pin("GPIO3", "I2C"),
                pin("GPIO14", "UART"),
                pin("GPIO15", "UART"),
                pin("5V", "POWER"),
                pin("GND", "GROUND"),
            ],
            ["raspberry", "pi", "pi4", "wifi", "linux"],
            ["rpi", "pi 4"],
            ["raspberry-pi-4"],
        ),
        comp(
            "teensy",
            "Teensy 4.1",
            "mcu",
            "PJRC",
            ["GPIO", "PWM", "UART", "I2C", "SPI", "ADC"],
            (3.3, 3.3),
            [pin("D13", "GPIO"), pin("3V3", "POWER"), pin("GND", "GROUND")],
            ["teensy", "mcu"],
            [],
            ["teensy"],
        ),
        comp(
            "microbit",
            "BBC micro:bit",
            "mcu",
            "BBC",
            ["GPIO", "PWM", "UART", "I2C", "SPI", "Bluetooth"],
            (3.3, 3.3),
            [pin("P0", "GPIO"), pin("P1", "GPIO"), pin("3V", "POWER"), pin("GND", "GROUND")],
            ["microbit", "micro:bit", "bbc", "mcu"],
            ["micro bit", "micro:bit"],
            ["microbit"],
        ),
    ]

    items += [
        comp(
            "dht11",
            "DHT11 Temperature Humidity Sensor",
            "sensor",
            "Aosong",
            ["GPIO", "Digital"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("DATA", "GPIO"), pin("GND", "GROUND")],
            ["temperature", "humidity", "dht", "sensor"],
            ["dht 11"],
            simulation={"supported": True, "model": "temperature_humidity"},
        ),
        comp(
            "dht22",
            "DHT22 Temperature Humidity Sensor",
            "sensor",
            "Aosong",
            ["GPIO", "Digital"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("DATA", "GPIO"), pin("GND", "GROUND")],
            ["temperature", "humidity", "dht", "sensor"],
            ["am2302", "dht 22"],
            simulation={"supported": True, "model": "temperature_humidity"},
        ),
        comp(
            "am2302",
            "AM2302 Temperature Humidity Sensor",
            "sensor",
            "Aosong",
            ["GPIO", "Digital"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("DATA", "GPIO"), pin("GND", "GROUND")],
            ["temperature", "humidity", "dht", "am2302", "sensor"],
            ["dht22"],
            simulation={"supported": True, "model": "temperature_humidity"},
        ),
        comp(
            "bmp280",
            "BMP280 Pressure Sensor",
            "sensor",
            "Bosch",
            ["I2C", "SPI"],
            (3.3, 3.3),
            [
                pin("VCC", "POWER"),
                pin("GND", "GROUND"),
                pin("SDA", "I2C"),
                pin("SCL", "I2C"),
            ],
            ["pressure", "barometer", "temperature", "sensor", "i2c"],
            ["bmp 280"],
        ),
        comp(
            "mpu6050",
            "MPU6050 IMU",
            "sensor",
            "InvenSense",
            ["I2C"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("GND", "GROUND"), pin("SDA", "I2C"), pin("SCL", "I2C")],
            ["imu", "gyro", "accelerometer", "sensor", "i2c"],
            ["mpu 6050"],
        ),
        comp(
            "hc-sr04",
            "HC-SR04 Ultrasonic",
            "sensor",
            "Generic",
            ["GPIO", "Digital"],
            (5, 5),
            [
                pin("VCC", "POWER"),
                pin("TRIG", "GPIO"),
                pin("ECHO", "GPIO"),
                pin("GND", "GROUND"),
            ],
            ["ultrasonic", "distance", "sensor"],
            ["hcsr04"],
        ),
        comp(
            "pir",
            "PIR Motion Sensor",
            "sensor",
            "Generic",
            ["GPIO", "Digital"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("OUT", "GPIO"), pin("GND", "GROUND")],
            ["motion", "pir", "sensor"],
            ["motion"],
        ),
        comp(
            "mq2",
            "MQ2 Gas Sensor",
            "sensor",
            "Winsen",
            ["Analog", "ADC", "GPIO"],
            (5, 5),
            [pin("VCC", "POWER"), pin("A0", "ADC"), pin("D0", "GPIO"), pin("GND", "GROUND")],
            ["gas", "smoke", "mq2", "sensor"],
            ["mq-2"],
        ),
        comp(
            "soil-moisture",
            "Soil Moisture Sensor",
            "sensor",
            "Generic",
            ["Analog", "ADC", "GPIO"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("A0", "ADC"), pin("GND", "GROUND")],
            ["soil", "moisture", "sensor"],
            ["soil"],
        ),
        comp(
            "ldr",
            "LDR Light Sensor",
            "sensor",
            "Generic",
            ["Analog", "ADC"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("SIG", "ADC"), pin("GND", "GROUND")],
            ["light", "ldr", "photoresistor", "sensor"],
            ["photoresistor"],
        ),
        comp(
            "ds18b20",
            "DS18B20 Temperature",
            "sensor",
            "Maxim",
            ["GPIO", "OneWire"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("DQ", "GPIO"), pin("GND", "GROUND")],
            ["temperature", "onewire", "sensor", "ds18b20"],
            ["ds18b20"],
        ),
    ]

    items += [
        comp(
            "led",
            "LED",
            "actuator",
            "Generic",
            ["GPIO", "Digital", "PWM"],
            (1.8, 5),
            [pin("ANODE", "GPIO"), pin("CATHODE", "GROUND")],
            ["led", "light", "actuator"],
            ["diode led"],
            simulation={"supported": True, "model": "led"},
        ),
        comp(
            "rgb-led",
            "RGB LED",
            "actuator",
            "Generic",
            ["GPIO", "PWM"],
            (3.3, 5),
            [pin("R", "PWM"), pin("G", "PWM"), pin("B", "PWM"), pin("GND", "GROUND")],
            ["led", "rgb", "actuator", "pwm"],
            ["rgb"],
            simulation={"supported": True, "model": "rgb_led"},
        ),
        comp(
            "relay",
            "Relay Module",
            "actuator",
            "Generic",
            ["GPIO", "Digital"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("IN", "GPIO"), pin("GND", "GROUND")],
            ["relay", "switch", "actuator"],
            simulation={"supported": True, "model": "relay"},
        ),
        comp(
            "servo",
            "Servo Motor",
            "actuator",
            "Generic",
            ["PWM", "GPIO"],
            (4.8, 6),
            [pin("VCC", "POWER"), pin("SIG", "PWM"), pin("GND", "GROUND")],
            ["servo", "motor", "actuator", "pwm"],
            ["sg90"],
            simulation={"supported": True, "model": "servo"},
        ),
        comp(
            "dc-motor",
            "DC Motor",
            "actuator",
            "Generic",
            ["GPIO", "PWM"],
            (3.3, 12),
            [pin("IN1", "GPIO"), pin("IN2", "GPIO"), pin("VCC", "POWER"), pin("GND", "GROUND")],
            ["motor", "dc", "actuator"],
            ["dcmotor"],
            simulation={"supported": True, "model": "dc_motor"},
        ),
        comp(
            "stepper-motor",
            "Stepper Motor",
            "actuator",
            "Generic",
            ["GPIO"],
            (5, 12),
            [
                pin("IN1", "GPIO"),
                pin("IN2", "GPIO"),
                pin("IN3", "GPIO"),
                pin("IN4", "GPIO"),
                pin("VCC", "POWER"),
                pin("GND", "GROUND"),
            ],
            ["motor", "stepper", "actuator"],
            ["stepper"],
            simulation={"supported": True, "model": "stepper"},
        ),
        comp(
            "buzzer",
            "Buzzer",
            "actuator",
            "Generic",
            ["GPIO", "PWM"],
            (3.3, 5),
            [pin("SIG", "GPIO"), pin("GND", "GROUND")],
            ["buzzer", "sound", "actuator"],
            ["beeper"],
            simulation={"supported": True, "model": "buzzer"},
        ),
    ]

    items += [
        comp(
            "hc-05",
            "Bluetooth HC-05",
            "communication",
            "Generic",
            ["UART", "Bluetooth"],
            (3.3, 5),
            [pin("VCC", "POWER"), pin("GND", "GROUND"), pin("TX", "UART"), pin("RX", "UART")],
            ["bluetooth", "uart", "hc05", "communication"],
            ["hc05"],
        ),
        comp(
            "nrf24l01",
            "NRF24L01",
            "communication",
            "Nordic",
            ["SPI"],
            (3.3, 3.3),
            [
                pin("VCC", "POWER"),
                pin("GND", "GROUND"),
                pin("CE", "GPIO"),
                pin("CSN", "SPI"),
                pin("SCK", "SPI"),
                pin("MOSI", "SPI"),
                pin("MISO", "SPI"),
            ],
            ["nrf", "radio", "spi", "communication", "wireless"],
            ["nrf24"],
        ),
        comp(
            "lora",
            "LoRa Module",
            "communication",
            "Semtech",
            ["SPI", "UART"],
            (3.3, 3.3),
            [
                pin("VCC", "POWER"),
                pin("GND", "GROUND"),
                pin("NSS", "SPI"),
                pin("SCK", "SPI"),
                pin("MOSI", "SPI"),
                pin("MISO", "SPI"),
            ],
            ["lora", "radio", "long range", "communication"],
            ["sx1278"],
        ),
        comp(
            "wifi-module",
            "WiFi Module",
            "communication",
            "Espressif",
            ["UART", "WiFi"],
            (3.3, 3.3),
            [pin("VCC", "POWER"), pin("GND", "GROUND"), pin("TX", "UART"), pin("RX", "UART")],
            ["wifi", "wireless", "communication", "esp"],
            ["esp-01"],
        ),
    ]

    items += [
        comp(
            "lcd-16x2",
            "LCD 16x2",
            "display",
            "Hitachi",
            ["I2C", "GPIO"],
            (5, 5),
            [pin("VCC", "POWER"), pin("GND", "GROUND"), pin("SDA", "I2C"), pin("SCL", "I2C")],
            ["lcd", "display", "16x2", "i2c"],
            ["lcd", "hd44780"],
            simulation={"supported": True, "model": "lcd"},
        ),
        comp(
            "oled-ssd1306",
            "OLED SSD1306",
            "display",
            "Solomon",
            ["I2C", "SPI"],
            (3.3, 3.3),
            [pin("VCC", "POWER"), pin("GND", "GROUND"), pin("SDA", "I2C"), pin("SCL", "I2C")],
            ["oled", "display", "ssd1306", "i2c"],
            ["ssd1306", "oled"],
            simulation={"supported": True, "model": "oled"},
        ),
        comp(
            "tft-display",
            "TFT Display",
            "display",
            "Generic",
            ["SPI"],
            (3.3, 3.3),
            [
                pin("VCC", "POWER"),
                pin("GND", "GROUND"),
                pin("CS", "SPI"),
                pin("MOSI", "SPI"),
                pin("SCK", "SPI"),
                pin("DC", "GPIO"),
            ],
            ["tft", "display", "lcd", "spi"],
            ["ili9341"],
            simulation={"supported": True, "model": "tft"},
        ),
    ]

    for c in items:
        (root / f"{c['id']}.json").write_text(json.dumps(c, indent=2), encoding="utf-8")
    print(f"wrote {len(items)} -> {root}")


if __name__ == "__main__":
    main()
